version: '3'
services:
  gogram:
    build: .
    links:
      - redis
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - 8000:8000
  redis:
    image: redis
    volumes:
      - ./redis:/data
